version: '3.9'

services:
  YiffBot_dev:
    image: dockerreg.m-loeffler.de/yiffbot:dev
    container_name: yiffbot_dev
    restart: always
    volumes:
      - yiffslutdata_dev:/app/data
    environment:
      TZ: Europe/Berlin
      DB_HOST: mariadb
      DB_USER: yiffslut
      DB_PASS: yiffslut
      DB_NAME: yiffslut
      DB_PORT: 3306

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadbdata_dev:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: yiffslut
      MYSQL_DATABASE: yiffslut
      MYSQL_USER: yiffslut
      MYSQL_PASSWORD: yiffslut
    

volumes:
  yiffslutdata_dev:
  mariadbdata_dev: