version: '3.9'

services:
  YiffBot_dev:
    image: dockerreg.m-loeffler.de/yiffbot:dev
    container_name: yiffbot_dev
    restart: always
    volumes:
      - yiffslutdata_dev:/app/data
    environment:
      TZ: Europe/Berlin
    env_file:
      - .env

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - mariadbdata_dev:/var/lib/mysql
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DB}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    

volumes:
  yiffslutdata_dev:
  mariadbdata_dev: