FROM node:20-alpine AS build
WORKDIR /app

COPY package.json .
COPY package-lock.json .
RUN npm i -g typescript
RUN npm i

COPY . .

RUN tsc


FROM node:20-alpine AS prod

WORKDIR /app

COPY --from=build /app/bin/ /app/bin
COPY --from=build /app/node_modules/ /app/node_modules/
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/package-lock.json /app/package-lock.json

CMD ["npm", "run", "start:prod"]